USE BOOKSTORE;

CREATE TABLE PUBLISHER (
    NAME VARCHAR(100) NOT NULL,

    CONSTRAINT PUBLISHER_PK_ID PRIMARY KEY (NAME)
);

CREATE TABLE BOOK (
    ISBN VARCHAR(50) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    PUBLICATION_DATE DATE NOT NULL,
    PUBLISHER_NAME VARCHAR(100) NOT NULL,

    CONSTRAINT BOOK_PK_ID PRIMARY KEY (ISBN),
    CONSTRAINT BOOK_FK_PUBLISHERID FOREIGN KEY (PUBLISHER_NAME) REFERENCES PUBLISHER (NAME)
);

CREATE TABLE CHAPTER (
    NUMBER INTEGER NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    BOOK_ISBN VARCHAR(50) NOT NULL,

    CONSTRAINT CHAPTER_PK_ID PRIMARY KEY (BOOK_ISBN, NUMBER),
    CONSTRAINT CHAPTER_FK_BOOKID FOREIGN KEY (BOOK_ISBN) REFERENCES BOOK (ISBN)
);
